/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type DayOfWeek = { 'tuesday' : null } |
  { 'wednesday' : null } |
  { 'saturday' : null } |
  { 'thursday' : null } |
  { 'sunday' : null } |
  { 'friday' : null } |
  { 'monday' : null };
export interface Note {
  'id' : NoteId,
  'title' : string,
  'body' : string,
  'timestamp' : Time,
}
export type NoteId = bigint;
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface ScheduleEntry {
  'id' : ScheduleId,
  'startTime' : bigint,
  'title' : string,
  'endTime' : bigint,
  'dayOfWeek' : DayOfWeek,
  'notes' : string,
}
export type ScheduleId = bigint;
export interface Task {
  'id' : TaskId,
  'title' : string,
  'completed' : boolean,
  'dueDate' : [] | [Time],
  'description' : string,
  'priority' : Priority,
}
export type TaskId = bigint;
export type Time = bigint;
export interface _SERVICE {
  'createNote' : ActorMethod<[string, string], NoteId>,
  'createScheduleEntry' : ActorMethod<
    [string, DayOfWeek, bigint, bigint, string],
    ScheduleId
  >,
  'createTask' : ActorMethod<[string, string, Priority, [] | [Time]], TaskId>,
  'deleteNote' : ActorMethod<[NoteId], undefined>,
  'deleteScheduleEntry' : ActorMethod<[ScheduleId], undefined>,
  'deleteTask' : ActorMethod<[TaskId], undefined>,
  'getAllNotes' : ActorMethod<[], Array<Note>>,
  'getAllScheduleEntries' : ActorMethod<[], Array<ScheduleEntry>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getNote' : ActorMethod<[NoteId], Note>,
  'getScheduleEntry' : ActorMethod<[ScheduleId], ScheduleEntry>,
  'getTask' : ActorMethod<[TaskId], Task>,
  'updateNote' : ActorMethod<[NoteId, string, string], undefined>,
  'updateScheduleEntry' : ActorMethod<
    [ScheduleId, string, DayOfWeek, bigint, bigint, string],
    undefined
  >,
  'updateTask' : ActorMethod<
    [TaskId, string, string, Priority, [] | [Time], boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];