/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const JobPostingId = IDL.Nat;
export const NoteId = IDL.Nat;
export const NotificationId = IDL.Nat;
export const DayOfWeek = IDL.Variant({
  'tuesday' : IDL.Null,
  'wednesday' : IDL.Null,
  'saturday' : IDL.Null,
  'thursday' : IDL.Null,
  'sunday' : IDL.Null,
  'friday' : IDL.Null,
  'monday' : IDL.Null,
});
export const ScheduleId = IDL.Nat;
export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Time = IDL.Int;
export const TaskId = IDL.Nat;
export const WorkEntryId = IDL.Nat;
export const JobStatus = IDL.Variant({
  'assigned' : IDL.Null,
  'deleted' : IDL.Null,
  'completed' : IDL.Null,
  'available' : IDL.Null,
});
export const JobPosting = IDL.Record({
  'id' : JobPostingId,
  'startTime' : IDL.Int,
  'status' : JobStatus,
  'title' : IDL.Text,
  'endTime' : IDL.Int,
  'date' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'address' : IDL.Text,
  'assignedWorkerAddress' : IDL.Text,
  'assignedWorkerPhone' : IDL.Text,
  'assignedWorkerName' : IDL.Text,
  'paymentAmount' : IDL.Float64,
});
export const Note = IDL.Record({
  'id' : NoteId,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'timestamp' : Time,
});
export const Notification = IDL.Record({
  'id' : NotificationId,
  'title' : IDL.Text,
  'notificationType' : IDL.Text,
  'jobId' : IDL.Nat,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const ScheduleEntry = IDL.Record({
  'id' : ScheduleId,
  'startTime' : IDL.Nat,
  'title' : IDL.Text,
  'endTime' : IDL.Nat,
  'dayOfWeek' : DayOfWeek,
  'notes' : IDL.Text,
});
export const Task = IDL.Record({
  'id' : TaskId,
  'title' : IDL.Text,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(Time),
  'description' : IDL.Text,
  'priority' : Priority,
});
export const WorkEntry = IDL.Record({
  'id' : WorkEntryId,
  'startTime' : IDL.Nat,
  'workType' : IDL.Text,
  'dailyPayment' : IDL.Float64,
  'endTime' : IDL.Nat,
  'date' : IDL.Text,
  'hoursWorked' : IDL.Float64,
  'createdAt' : Time,
  'notes' : IDL.Text,
  'workerName' : IDL.Text,
});

export const idlService = IDL.Service({
  'assignJobPosting' : IDL.Func(
      [JobPostingId, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'completeJobPosting' : IDL.Func([JobPostingId], [IDL.Bool], []),
  'createJobPosting' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Int, IDL.Float64, IDL.Text],
      [JobPostingId],
      [],
    ),
  'createNote' : IDL.Func([IDL.Text, IDL.Text], [NoteId], []),
  'createNotification' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [NotificationId],
      [],
    ),
  'createScheduleEntry' : IDL.Func(
      [IDL.Text, DayOfWeek, IDL.Nat, IDL.Nat, IDL.Text],
      [ScheduleId],
      [],
    ),
  'createTask' : IDL.Func(
      [IDL.Text, IDL.Text, Priority, IDL.Opt(Time)],
      [TaskId],
      [],
    ),
  'createWorkEntry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
      ],
      [WorkEntryId],
      [],
    ),
  'deleteJobPosting' : IDL.Func([JobPostingId], [], []),
  'deleteNote' : IDL.Func([NoteId], [], []),
  'deleteNotification' : IDL.Func([NotificationId], [], []),
  'deleteScheduleEntry' : IDL.Func([ScheduleId], [], []),
  'deleteTask' : IDL.Func([TaskId], [], []),
  'deleteWorkEntry' : IDL.Func([WorkEntryId], [], []),
  'getAllJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
  'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getAllNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getAllScheduleEntries' : IDL.Func([], [IDL.Vec(ScheduleEntry)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAllWorkEntries' : IDL.Func([], [IDL.Vec(WorkEntry)], ['query']),
  'getAssignedJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
  'getAvailableJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
  'getNote' : IDL.Func([NoteId], [Note], ['query']),
  'getScheduleEntry' : IDL.Func([ScheduleId], [ScheduleEntry], ['query']),
  'getTask' : IDL.Func([TaskId], [Task], ['query']),
  'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getWorkEntriesByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(WorkEntry)],
      ['query'],
    ),
  'getWorkEntriesByDateRange' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(WorkEntry)],
      ['query'],
    ),
  'getWorkEntriesByWorker' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(WorkEntry)],
      ['query'],
    ),
  'getWorkEntry' : IDL.Func([WorkEntryId], [WorkEntry], ['query']),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markNotificationRead' : IDL.Func([NotificationId], [], []),
  'updateNote' : IDL.Func([NoteId, IDL.Text, IDL.Text], [], []),
  'updateScheduleEntry' : IDL.Func(
      [ScheduleId, IDL.Text, DayOfWeek, IDL.Nat, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'updateTask' : IDL.Func(
      [TaskId, IDL.Text, IDL.Text, Priority, IDL.Opt(Time), IDL.Bool],
      [],
      [],
    ),
  'updateWorkEntry' : IDL.Func(
      [
        WorkEntryId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const JobPostingId = IDL.Nat;
  const NoteId = IDL.Nat;
  const NotificationId = IDL.Nat;
  const DayOfWeek = IDL.Variant({
    'tuesday' : IDL.Null,
    'wednesday' : IDL.Null,
    'saturday' : IDL.Null,
    'thursday' : IDL.Null,
    'sunday' : IDL.Null,
    'friday' : IDL.Null,
    'monday' : IDL.Null,
  });
  const ScheduleId = IDL.Nat;
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Time = IDL.Int;
  const TaskId = IDL.Nat;
  const WorkEntryId = IDL.Nat;
  const JobStatus = IDL.Variant({
    'assigned' : IDL.Null,
    'deleted' : IDL.Null,
    'completed' : IDL.Null,
    'available' : IDL.Null,
  });
  const JobPosting = IDL.Record({
    'id' : JobPostingId,
    'startTime' : IDL.Int,
    'status' : JobStatus,
    'title' : IDL.Text,
    'endTime' : IDL.Int,
    'date' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'address' : IDL.Text,
    'assignedWorkerAddress' : IDL.Text,
    'assignedWorkerPhone' : IDL.Text,
    'assignedWorkerName' : IDL.Text,
    'paymentAmount' : IDL.Float64,
  });
  const Note = IDL.Record({
    'id' : NoteId,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'timestamp' : Time,
  });
  const Notification = IDL.Record({
    'id' : NotificationId,
    'title' : IDL.Text,
    'notificationType' : IDL.Text,
    'jobId' : IDL.Nat,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const ScheduleEntry = IDL.Record({
    'id' : ScheduleId,
    'startTime' : IDL.Nat,
    'title' : IDL.Text,
    'endTime' : IDL.Nat,
    'dayOfWeek' : DayOfWeek,
    'notes' : IDL.Text,
  });
  const Task = IDL.Record({
    'id' : TaskId,
    'title' : IDL.Text,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(Time),
    'description' : IDL.Text,
    'priority' : Priority,
  });
  const WorkEntry = IDL.Record({
    'id' : WorkEntryId,
    'startTime' : IDL.Nat,
    'workType' : IDL.Text,
    'dailyPayment' : IDL.Float64,
    'endTime' : IDL.Nat,
    'date' : IDL.Text,
    'hoursWorked' : IDL.Float64,
    'createdAt' : Time,
    'notes' : IDL.Text,
    'workerName' : IDL.Text,
  });
  
  return IDL.Service({
    'assignJobPosting' : IDL.Func(
        [JobPostingId, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'completeJobPosting' : IDL.Func([JobPostingId], [IDL.Bool], []),
    'createJobPosting' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Int, IDL.Float64, IDL.Text],
        [JobPostingId],
        [],
      ),
    'createNote' : IDL.Func([IDL.Text, IDL.Text], [NoteId], []),
    'createNotification' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [NotificationId],
        [],
      ),
    'createScheduleEntry' : IDL.Func(
        [IDL.Text, DayOfWeek, IDL.Nat, IDL.Nat, IDL.Text],
        [ScheduleId],
        [],
      ),
    'createTask' : IDL.Func(
        [IDL.Text, IDL.Text, Priority, IDL.Opt(Time)],
        [TaskId],
        [],
      ),
    'createWorkEntry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
        ],
        [WorkEntryId],
        [],
      ),
    'deleteJobPosting' : IDL.Func([JobPostingId], [], []),
    'deleteNote' : IDL.Func([NoteId], [], []),
    'deleteNotification' : IDL.Func([NotificationId], [], []),
    'deleteScheduleEntry' : IDL.Func([ScheduleId], [], []),
    'deleteTask' : IDL.Func([TaskId], [], []),
    'deleteWorkEntry' : IDL.Func([WorkEntryId], [], []),
    'getAllJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
    'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getAllNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getAllScheduleEntries' : IDL.Func([], [IDL.Vec(ScheduleEntry)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAllWorkEntries' : IDL.Func([], [IDL.Vec(WorkEntry)], ['query']),
    'getAssignedJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
    'getAvailableJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
    'getNote' : IDL.Func([NoteId], [Note], ['query']),
    'getScheduleEntry' : IDL.Func([ScheduleId], [ScheduleEntry], ['query']),
    'getTask' : IDL.Func([TaskId], [Task], ['query']),
    'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getWorkEntriesByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(WorkEntry)],
        ['query'],
      ),
    'getWorkEntriesByDateRange' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(WorkEntry)],
        ['query'],
      ),
    'getWorkEntriesByWorker' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(WorkEntry)],
        ['query'],
      ),
    'getWorkEntry' : IDL.Func([WorkEntryId], [WorkEntry], ['query']),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markNotificationRead' : IDL.Func([NotificationId], [], []),
    'updateNote' : IDL.Func([NoteId, IDL.Text, IDL.Text], [], []),
    'updateScheduleEntry' : IDL.Func(
        [ScheduleId, IDL.Text, DayOfWeek, IDL.Nat, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'updateTask' : IDL.Func(
        [TaskId, IDL.Text, IDL.Text, Priority, IDL.Opt(Time), IDL.Bool],
        [],
        [],
      ),
    'updateWorkEntry' : IDL.Func(
        [
          WorkEntryId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };