/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : BookingId,
  'status' : BookingStatus,
  'serviceType' : string,
  'workerId' : bigint,
  'userId' : bigint,
  'note' : string,
  'createdAt' : Time,
  'workerName' : string,
}
export type BookingId = bigint;
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export type DayOfWeek = { 'tuesday' : null } |
  { 'wednesday' : null } |
  { 'saturday' : null } |
  { 'thursday' : null } |
  { 'sunday' : null } |
  { 'friday' : null } |
  { 'monday' : null };
export interface JobApplication {
  'id' : JobApplicationId,
  'status' : string,
  'appliedAt' : Time,
  'applicantName' : string,
  'applicantPhone' : string,
  'vacancyId' : JobVacancyId,
  'postedByUserId' : bigint,
  'applicantUserId' : bigint,
}
export type JobApplicationId = bigint;
export interface JobPosting {
  'id' : JobPostingId,
  'startTime' : bigint,
  'status' : JobStatus,
  'title' : string,
  'endTime' : bigint,
  'date' : string,
  'createdAt' : Time,
  'description' : string,
  'address' : string,
  'assignedWorkerAddress' : string,
  'assignedWorkerPhone' : string,
  'assignedWorkerName' : string,
  'paymentAmount' : number,
}
export type JobPostingId = bigint;
export type JobStatus = { 'assigned' : null } |
  { 'deleted' : null } |
  { 'completed' : null } |
  { 'available' : null };
export type JobVacancyId = bigint;
export type JobVacancyStatus = { 'closed' : null } |
  { 'open' : null };
export interface JobVacancyWithOwner {
  'id' : JobVacancyId,
  'status' : JobVacancyStatus,
  'title' : string,
  'postedAt' : Time,
  'salary' : [] | [string],
  'description' : string,
  'postedByUserId' : bigint,
  'companyName' : string,
  'category' : string,
  'location' : string,
  'contactPhone' : [] | [string],
}
export interface Note {
  'id' : NoteId,
  'title' : string,
  'body' : string,
  'timestamp' : Time,
}
export type NoteId = bigint;
export interface Notification {
  'id' : NotificationId,
  'title' : string,
  'notificationType' : string,
  'jobId' : bigint,
  'isRead' : boolean,
  'message' : string,
  'timestamp' : Time,
}
export type NotificationId = bigint;
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface RentalProperty {
  'id' : RentalPropertyId,
  'status' : RentalStatus,
  'title' : string,
  'ownerName' : string,
  'createdAt' : Time,
  'numberOfRooms' : bigint,
  'description' : string,
  'pricePerMonth' : number,
  'location' : string,
  'contactPhone' : string,
}
export type RentalPropertyId = bigint;
export type RentalStatus = { 'rented' : null } |
  { 'available' : null };
export interface RentalWithOwner {
  'id' : RentalPropertyId,
  'status' : RentalStatus,
  'title' : string,
  'ownerName' : string,
  'createdAt' : Time,
  'numberOfRooms' : bigint,
  'description' : string,
  'postedByUserId' : bigint,
  'pricePerMonth' : number,
  'location' : string,
  'contactPhone' : string,
}
export interface ScheduleEntry {
  'id' : ScheduleId,
  'startTime' : bigint,
  'title' : string,
  'endTime' : bigint,
  'dayOfWeek' : DayOfWeek,
  'notes' : string,
}
export type ScheduleId = bigint;
export interface Task {
  'id' : TaskId,
  'title' : string,
  'completed' : boolean,
  'dueDate' : [] | [Time],
  'description' : string,
  'priority' : Priority,
}
export type TaskId = bigint;
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserAccount {
  'id' : bigint,
  'emailOrPhone' : string,
  'name' : string,
  'createdAt' : Time,
  'role' : UserRole,
  'passwordHash' : string,
}
export type UserId = bigint;
export interface UserNotification {
  'id' : UserNotificationId,
  'title' : string,
  'receiverUserId' : bigint,
  'jobId' : bigint,
  'isRead' : boolean,
  'message' : string,
  'timestamp' : bigint,
  'senderUserId' : bigint,
}
export type UserNotificationId = bigint;
export interface UserProfile {
  'userId' : [] | [bigint],
  'name' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'worker' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkEntry {
  'id' : WorkEntryId,
  'startTime' : bigint,
  'workType' : string,
  'dailyPayment' : number,
  'endTime' : bigint,
  'date' : string,
  'hoursWorked' : number,
  'createdAt' : Time,
  'notes' : string,
  'workerName' : string,
}
export type WorkEntryId = bigint;
export type WorkerId = bigint;
export interface WorkerProfile {
  'id' : WorkerId,
  'status' : WorkerStatus,
  'latitude' : number,
  'userId' : bigint,
  'name' : string,
  'createdAt' : Time,
  'profession' : string,
  'longitude' : number,
  'rating' : number,
  'phone' : string,
  'location' : string,
}
export type WorkerStatus = { 'active' : null } |
  { 'blocked' : null } |
  { 'inactive' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptBooking' : ActorMethod<[BookingId], boolean>,
  'applyToVacancy' : ActorMethod<
    [JobVacancyId, bigint, string, string],
    JobApplicationId
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'assignJobPosting' : ActorMethod<
    [JobPostingId, string, string, string],
    boolean
  >,
  'cancelBooking' : ActorMethod<[BookingId], boolean>,
  'closeJobVacancy' : ActorMethod<[JobVacancyId], undefined>,
  'completeJobPosting' : ActorMethod<[JobPostingId], boolean>,
  'createBooking' : ActorMethod<
    [bigint, bigint, string, string, string],
    BookingId
  >,
  'createJobPosting' : ActorMethod<
    [string, string, string, bigint, bigint, number, string],
    JobPostingId
  >,
  'createJobVacancy' : ActorMethod<
    [
      string,
      string,
      string,
      [] | [string],
      string,
      string,
      bigint,
      [] | [string],
    ],
    JobVacancyId
  >,
  'createNote' : ActorMethod<[string, string], NoteId>,
  'createNotification' : ActorMethod<
    [string, string, string, bigint],
    NotificationId
  >,
  'createRentalProperty' : ActorMethod<
    [string, string, string, number, bigint, string, string, bigint],
    RentalPropertyId
  >,
  'createScheduleEntry' : ActorMethod<
    [string, DayOfWeek, bigint, bigint, string],
    ScheduleId
  >,
  'createTask' : ActorMethod<[string, string, Priority, [] | [Time]], TaskId>,
  'createUserNotification' : ActorMethod<
    [bigint, bigint, bigint, string, string],
    UserNotificationId
  >,
  'createWorkEntry' : ActorMethod<
    [string, string, string, bigint, bigint, number, number, string],
    WorkEntryId
  >,
  'createWorkerProfile' : ActorMethod<
    [bigint, string, string, string, number, string, number, number],
    bigint
  >,
  'deleteJobVacancy' : ActorMethod<[JobVacancyId, bigint], undefined>,
  'deleteNote' : ActorMethod<[NoteId], undefined>,
  'deleteNotification' : ActorMethod<[NotificationId], undefined>,
  'deleteRentalProperty' : ActorMethod<[RentalPropertyId, bigint], undefined>,
  'deleteScheduleEntry' : ActorMethod<[ScheduleId], undefined>,
  'deleteTask' : ActorMethod<[TaskId], undefined>,
  'deleteUserNotification' : ActorMethod<[UserNotificationId], undefined>,
  'deleteWorkEntry' : ActorMethod<[WorkEntryId], undefined>,
  'generateOtp' : ActorMethod<[string], boolean>,
  'getOtpForPhone' : ActorMethod<[string], string>,
  'getActiveWorkers' : ActorMethod<[], Array<WorkerProfile>>,
  'getAllJobPostings' : ActorMethod<[], Array<JobPosting>>,
  'getAllJobVacancies' : ActorMethod<[], Array<JobVacancyWithOwner>>,
  'getAllNotes' : ActorMethod<[], Array<Note>>,
  'getAllNotifications' : ActorMethod<[], Array<Notification>>,
  'getAllRentals' : ActorMethod<[], Array<RentalProperty>>,
  'getAllScheduleEntries' : ActorMethod<[], Array<ScheduleEntry>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getAllUsers' : ActorMethod<[], Array<UserAccount>>,
  'getAllWorkEntries' : ActorMethod<[], Array<WorkEntry>>,
  'getAllWorkerProfiles' : ActorMethod<[], Array<WorkerProfile>>,
  'getApplicationsForVacancy' : ActorMethod<
    [JobVacancyId],
    Array<JobApplication>
  >,
  'getAssignedJobPostings' : ActorMethod<[], Array<JobPosting>>,
  'getAvailableJobPostings' : ActorMethod<[], Array<JobPosting>>,
  'getAvailableRentals' : ActorMethod<[], Array<RentalWithOwner>>,
  'getBookingsForUser' : ActorMethod<[bigint], Array<Booking>>,
  'getBookingsForWorker' : ActorMethod<[bigint], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getJobVacanciesByCategory' : ActorMethod<
    [string],
    Array<JobVacancyWithOwner>
  >,
  'getJobVacanciesByLocation' : ActorMethod<
    [string],
    Array<JobVacancyWithOwner>
  >,
  'getNotInterestedJobIds' : ActorMethod<[string], Array<JobPostingId>>,
  'getNote' : ActorMethod<[NoteId], Note>,
  'getNotificationsForUser' : ActorMethod<[bigint], Array<UserNotification>>,
  'getOpenJobVacancies' : ActorMethod<[], Array<JobVacancyWithOwner>>,
  'getRentalsByLocation' : ActorMethod<[string], Array<RentalProperty>>,
  'getScheduleEntry' : ActorMethod<[ScheduleId], ScheduleEntry>,
  'getTask' : ActorMethod<[TaskId], Task>,
  'getUnreadCount' : ActorMethod<[], bigint>,
  'getUnreadCountForUser' : ActorMethod<[bigint], bigint>,
  'getUserApplications' : ActorMethod<[bigint], Array<JobApplication>>,
  'getUserById' : ActorMethod<[UserId], [] | [UserAccount]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkEntriesByDate' : ActorMethod<[string], Array<WorkEntry>>,
  'getWorkEntriesByDateRange' : ActorMethod<[string, string], Array<WorkEntry>>,
  'getWorkEntriesByWorker' : ActorMethod<[string], Array<WorkEntry>>,
  'getWorkEntry' : ActorMethod<[WorkEntryId], WorkEntry>,
  'getWorkerProfileByUserId' : ActorMethod<[bigint], [] | [WorkerProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isSmsConfigured' : ActorMethod<[], boolean>,
  'login' : ActorMethod<
    [string, string],
    { 'ok' : { 'userId' : UserId, 'role' : UserRole } } |
      { 'err' : string }
  >,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markAllUserNotificationsRead' : ActorMethod<[bigint], undefined>,
  'markNotificationRead' : ActorMethod<[NotificationId], undefined>,
  'markUserNotificationRead' : ActorMethod<[UserNotificationId], undefined>,
  'register' : ActorMethod<
    [string, string, string, UserRole],
    { 'ok' : UserId } |
      { 'err' : string }
  >,
  'rejectBooking' : ActorMethod<[BookingId], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setJobPreference' : ActorMethod<[string, JobPostingId, boolean], undefined>,
  'setTwilioConfig' : ActorMethod<[string, string, string], undefined>,
  'setWorkerStatus' : ActorMethod<[bigint, WorkerStatus], boolean>,
  'transformOtpResponse' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'updateJobVacancy' : ActorMethod<
    [
      JobVacancyId,
      string,
      string,
      string,
      [] | [string],
      string,
      string,
      bigint,
    ],
    undefined
  >,
  'updateNote' : ActorMethod<[NoteId, string, string], undefined>,
  'updateRentalStatus' : ActorMethod<
    [RentalPropertyId, RentalStatus],
    undefined
  >,
  'updateScheduleEntry' : ActorMethod<
    [ScheduleId, string, DayOfWeek, bigint, bigint, string],
    undefined
  >,
  'updateTask' : ActorMethod<
    [TaskId, string, string, Priority, [] | [Time], boolean],
    undefined
  >,
  'updateWorkEntry' : ActorMethod<
    [
      WorkEntryId,
      string,
      string,
      string,
      bigint,
      bigint,
      number,
      number,
      string,
    ],
    undefined
  >,
  'updateWorkerLocation' : ActorMethod<[WorkerId, number, number], boolean>,
  'updateWorkerStatus' : ActorMethod<[WorkerId, boolean], boolean>,
  'verifyOtp' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];