/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type DayOfWeek = { 'tuesday' : null } |
  { 'wednesday' : null } |
  { 'saturday' : null } |
  { 'thursday' : null } |
  { 'sunday' : null } |
  { 'friday' : null } |
  { 'monday' : null };
export interface JobApplication {
  'id' : JobApplicationId,
  'appliedAt' : Time,
  'applicantName' : string,
  'applicantPhone' : string,
  'vacancyId' : JobVacancyId,
}
export type JobApplicationId = bigint;
export interface JobPosting {
  'id' : JobPostingId,
  'startTime' : bigint,
  'status' : JobStatus,
  'title' : string,
  'endTime' : bigint,
  'date' : string,
  'createdAt' : Time,
  'description' : string,
  'address' : string,
  'assignedWorkerAddress' : string,
  'assignedWorkerPhone' : string,
  'assignedWorkerName' : string,
  'paymentAmount' : number,
}
export type JobPostingId = bigint;
export type JobStatus = { 'assigned' : null } |
  { 'deleted' : null } |
  { 'completed' : null } |
  { 'available' : null };
export interface JobVacancy {
  'id' : JobVacancyId,
  'status' : JobVacancyStatus,
  'title' : string,
  'postedAt' : Time,
  'salary' : [] | [string],
  'description' : string,
  'companyName' : string,
  'category' : string,
  'location' : string,
}
export type JobVacancyId = bigint;
export type JobVacancyStatus = { 'closed' : null } |
  { 'open' : null };
export interface Note {
  'id' : NoteId,
  'title' : string,
  'body' : string,
  'timestamp' : Time,
}
export type NoteId = bigint;
export interface Notification {
  'id' : NotificationId,
  'title' : string,
  'notificationType' : string,
  'jobId' : bigint,
  'isRead' : boolean,
  'message' : string,
  'timestamp' : Time,
}
export type NotificationId = bigint;
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface RentalProperty {
  'id' : RentalPropertyId,
  'status' : RentalStatus,
  'title' : string,
  'ownerName' : string,
  'createdAt' : Time,
  'numberOfRooms' : bigint,
  'description' : string,
  'pricePerMonth' : number,
  'location' : string,
  'contactPhone' : string,
}
export type RentalPropertyId = bigint;
export type RentalStatus = { 'rented' : null } |
  { 'available' : null };
export interface ScheduleEntry {
  'id' : ScheduleId,
  'startTime' : bigint,
  'title' : string,
  'endTime' : bigint,
  'dayOfWeek' : DayOfWeek,
  'notes' : string,
}
export type ScheduleId = bigint;
export interface Task {
  'id' : TaskId,
  'title' : string,
  'completed' : boolean,
  'dueDate' : [] | [Time],
  'description' : string,
  'priority' : Priority,
}
export type TaskId = bigint;
export type Time = bigint;
export interface WorkEntry {
  'id' : WorkEntryId,
  'startTime' : bigint,
  'workType' : string,
  'dailyPayment' : number,
  'endTime' : bigint,
  'date' : string,
  'hoursWorked' : number,
  'createdAt' : Time,
  'notes' : string,
  'workerName' : string,
}
export type WorkEntryId = bigint;
export interface _SERVICE {
  'applyToVacancy' : ActorMethod<
    [JobVacancyId, string, string],
    JobApplicationId
  >,
  'assignJobPosting' : ActorMethod<
    [JobPostingId, string, string, string],
    boolean
  >,
  'closeJobVacancy' : ActorMethod<[JobVacancyId], undefined>,
  'completeJobPosting' : ActorMethod<[JobPostingId], boolean>,
  'createJobPosting' : ActorMethod<
    [string, string, string, bigint, bigint, number, string],
    JobPostingId
  >,
  'createJobVacancy' : ActorMethod<
    [string, string, string, [] | [string], string, string],
    JobVacancyId
  >,
  'createNote' : ActorMethod<[string, string], NoteId>,
  'createNotification' : ActorMethod<
    [string, string, string, bigint],
    NotificationId
  >,
  'createRentalProperty' : ActorMethod<
    [string, string, string, number, bigint, string, string],
    RentalPropertyId
  >,
  'createScheduleEntry' : ActorMethod<
    [string, DayOfWeek, bigint, bigint, string],
    ScheduleId
  >,
  'createTask' : ActorMethod<[string, string, Priority, [] | [Time]], TaskId>,
  'createWorkEntry' : ActorMethod<
    [string, string, string, bigint, bigint, number, number, string],
    WorkEntryId
  >,
  'deleteJobPosting' : ActorMethod<[JobPostingId], undefined>,
  'deleteJobVacancy' : ActorMethod<[JobVacancyId], undefined>,
  'deleteNote' : ActorMethod<[NoteId], undefined>,
  'deleteNotification' : ActorMethod<[NotificationId], undefined>,
  'deleteRentalProperty' : ActorMethod<[RentalPropertyId], undefined>,
  'deleteScheduleEntry' : ActorMethod<[ScheduleId], undefined>,
  'deleteTask' : ActorMethod<[TaskId], undefined>,
  'deleteWorkEntry' : ActorMethod<[WorkEntryId], undefined>,
  'getAllJobPostings' : ActorMethod<[], Array<JobPosting>>,
  'getAllJobVacancies' : ActorMethod<[], Array<JobVacancy>>,
  'getAllNotes' : ActorMethod<[], Array<Note>>,
  'getAllNotifications' : ActorMethod<[], Array<Notification>>,
  'getAllRentals' : ActorMethod<[], Array<RentalProperty>>,
  'getAllScheduleEntries' : ActorMethod<[], Array<ScheduleEntry>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getAllWorkEntries' : ActorMethod<[], Array<WorkEntry>>,
  'getApplicationsForVacancy' : ActorMethod<
    [JobVacancyId],
    Array<JobApplication>
  >,
  'getAssignedJobPostings' : ActorMethod<[], Array<JobPosting>>,
  'getAvailableJobPostings' : ActorMethod<[], Array<JobPosting>>,
  'getAvailableJobPostingsForWorker' : ActorMethod<[string], Array<JobPosting>>,
  'getAvailableRentals' : ActorMethod<[], Array<RentalProperty>>,
  'getJobVacanciesByCategory' : ActorMethod<[string], Array<JobVacancy>>,
  'getJobVacanciesByLocation' : ActorMethod<[string], Array<JobVacancy>>,
  'getNotInterestedJobIds' : ActorMethod<[string], Array<JobPostingId>>,
  'getNote' : ActorMethod<[NoteId], Note>,
  'getOpenJobVacancies' : ActorMethod<[], Array<JobVacancy>>,
  'getRentalsByLocation' : ActorMethod<[string], Array<RentalProperty>>,
  'getScheduleEntry' : ActorMethod<[ScheduleId], ScheduleEntry>,
  'getTask' : ActorMethod<[TaskId], Task>,
  'getUnreadCount' : ActorMethod<[], bigint>,
  'getWorkEntriesByDate' : ActorMethod<[string], Array<WorkEntry>>,
  'getWorkEntriesByDateRange' : ActorMethod<[string, string], Array<WorkEntry>>,
  'getWorkEntriesByWorker' : ActorMethod<[string], Array<WorkEntry>>,
  'getWorkEntry' : ActorMethod<[WorkEntryId], WorkEntry>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markNotificationRead' : ActorMethod<[NotificationId], undefined>,
  'setJobPreference' : ActorMethod<[string, JobPostingId, boolean], undefined>,
  'updateNote' : ActorMethod<[NoteId, string, string], undefined>,
  'updateRentalStatus' : ActorMethod<
    [RentalPropertyId, RentalStatus],
    undefined
  >,
  'updateScheduleEntry' : ActorMethod<
    [ScheduleId, string, DayOfWeek, bigint, bigint, string],
    undefined
  >,
  'updateTask' : ActorMethod<
    [TaskId, string, string, Priority, [] | [Time], boolean],
    undefined
  >,
  'updateWorkEntry' : ActorMethod<
    [
      WorkEntryId,
      string,
      string,
      string,
      bigint,
      bigint,
      number,
      number,
      string,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];