/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const NoteId = IDL.Nat;
export const DayOfWeek = IDL.Variant({
  'tuesday' : IDL.Null,
  'wednesday' : IDL.Null,
  'saturday' : IDL.Null,
  'thursday' : IDL.Null,
  'sunday' : IDL.Null,
  'friday' : IDL.Null,
  'monday' : IDL.Null,
});
export const ScheduleId = IDL.Nat;
export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Time = IDL.Int;
export const TaskId = IDL.Nat;
export const Note = IDL.Record({
  'id' : NoteId,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'timestamp' : Time,
});
export const ScheduleEntry = IDL.Record({
  'id' : ScheduleId,
  'startTime' : IDL.Nat,
  'title' : IDL.Text,
  'endTime' : IDL.Nat,
  'dayOfWeek' : DayOfWeek,
  'notes' : IDL.Text,
});
export const Task = IDL.Record({
  'id' : TaskId,
  'title' : IDL.Text,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(Time),
  'description' : IDL.Text,
  'priority' : Priority,
});

export const idlService = IDL.Service({
  'createNote' : IDL.Func([IDL.Text, IDL.Text], [NoteId], []),
  'createScheduleEntry' : IDL.Func(
      [IDL.Text, DayOfWeek, IDL.Nat, IDL.Nat, IDL.Text],
      [ScheduleId],
      [],
    ),
  'createTask' : IDL.Func(
      [IDL.Text, IDL.Text, Priority, IDL.Opt(Time)],
      [TaskId],
      [],
    ),
  'deleteNote' : IDL.Func([NoteId], [], []),
  'deleteScheduleEntry' : IDL.Func([ScheduleId], [], []),
  'deleteTask' : IDL.Func([TaskId], [], []),
  'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getAllScheduleEntries' : IDL.Func([], [IDL.Vec(ScheduleEntry)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getNote' : IDL.Func([NoteId], [Note], ['query']),
  'getScheduleEntry' : IDL.Func([ScheduleId], [ScheduleEntry], ['query']),
  'getTask' : IDL.Func([TaskId], [Task], ['query']),
  'updateNote' : IDL.Func([NoteId, IDL.Text, IDL.Text], [], []),
  'updateScheduleEntry' : IDL.Func(
      [ScheduleId, IDL.Text, DayOfWeek, IDL.Nat, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'updateTask' : IDL.Func(
      [TaskId, IDL.Text, IDL.Text, Priority, IDL.Opt(Time), IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const NoteId = IDL.Nat;
  const DayOfWeek = IDL.Variant({
    'tuesday' : IDL.Null,
    'wednesday' : IDL.Null,
    'saturday' : IDL.Null,
    'thursday' : IDL.Null,
    'sunday' : IDL.Null,
    'friday' : IDL.Null,
    'monday' : IDL.Null,
  });
  const ScheduleId = IDL.Nat;
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Time = IDL.Int;
  const TaskId = IDL.Nat;
  const Note = IDL.Record({
    'id' : NoteId,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'timestamp' : Time,
  });
  const ScheduleEntry = IDL.Record({
    'id' : ScheduleId,
    'startTime' : IDL.Nat,
    'title' : IDL.Text,
    'endTime' : IDL.Nat,
    'dayOfWeek' : DayOfWeek,
    'notes' : IDL.Text,
  });
  const Task = IDL.Record({
    'id' : TaskId,
    'title' : IDL.Text,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(Time),
    'description' : IDL.Text,
    'priority' : Priority,
  });
  
  return IDL.Service({
    'createNote' : IDL.Func([IDL.Text, IDL.Text], [NoteId], []),
    'createScheduleEntry' : IDL.Func(
        [IDL.Text, DayOfWeek, IDL.Nat, IDL.Nat, IDL.Text],
        [ScheduleId],
        [],
      ),
    'createTask' : IDL.Func(
        [IDL.Text, IDL.Text, Priority, IDL.Opt(Time)],
        [TaskId],
        [],
      ),
    'deleteNote' : IDL.Func([NoteId], [], []),
    'deleteScheduleEntry' : IDL.Func([ScheduleId], [], []),
    'deleteTask' : IDL.Func([TaskId], [], []),
    'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getAllScheduleEntries' : IDL.Func([], [IDL.Vec(ScheduleEntry)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getNote' : IDL.Func([NoteId], [Note], ['query']),
    'getScheduleEntry' : IDL.Func([ScheduleId], [ScheduleEntry], ['query']),
    'getTask' : IDL.Func([TaskId], [Task], ['query']),
    'updateNote' : IDL.Func([NoteId, IDL.Text, IDL.Text], [], []),
    'updateScheduleEntry' : IDL.Func(
        [ScheduleId, IDL.Text, DayOfWeek, IDL.Nat, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'updateTask' : IDL.Func(
        [TaskId, IDL.Text, IDL.Text, Priority, IDL.Opt(Time), IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };