/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BookingId = IDL.Nat;
export const JobVacancyId = IDL.Nat;
export const JobApplicationId = IDL.Nat;
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const JobPostingId = IDL.Nat;
export const NoteId = IDL.Nat;
export const NotificationId = IDL.Nat;
export const RentalPropertyId = IDL.Nat;
export const DayOfWeek = IDL.Variant({
  'tuesday' : IDL.Null,
  'wednesday' : IDL.Null,
  'saturday' : IDL.Null,
  'thursday' : IDL.Null,
  'sunday' : IDL.Null,
  'friday' : IDL.Null,
  'monday' : IDL.Null,
});
export const ScheduleId = IDL.Nat;
export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Time = IDL.Int;
export const TaskId = IDL.Nat;
export const UserNotificationId = IDL.Nat;
export const WorkEntryId = IDL.Nat;
export const WorkerId = IDL.Nat;
export const WorkerStatus = IDL.Variant({
  'active' : IDL.Null,
  'blocked' : IDL.Null,
  'inactive' : IDL.Null,
});
export const WorkerProfile = IDL.Record({
  'id' : WorkerId,
  'status' : WorkerStatus,
  'latitude' : IDL.Float64,
  'userId' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'profession' : IDL.Text,
  'longitude' : IDL.Float64,
  'rating' : IDL.Float64,
  'phone' : IDL.Text,
  'location' : IDL.Text,
});
export const JobStatus = IDL.Variant({
  'assigned' : IDL.Null,
  'deleted' : IDL.Null,
  'completed' : IDL.Null,
  'available' : IDL.Null,
});
export const JobPosting = IDL.Record({
  'id' : JobPostingId,
  'startTime' : IDL.Int,
  'status' : JobStatus,
  'title' : IDL.Text,
  'endTime' : IDL.Int,
  'date' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'address' : IDL.Text,
  'assignedWorkerAddress' : IDL.Text,
  'assignedWorkerPhone' : IDL.Text,
  'assignedWorkerName' : IDL.Text,
  'paymentAmount' : IDL.Float64,
});
export const JobVacancyStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
});
export const JobVacancyWithOwner = IDL.Record({
  'id' : JobVacancyId,
  'status' : JobVacancyStatus,
  'title' : IDL.Text,
  'postedAt' : Time,
  'salary' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'postedByUserId' : IDL.Nat,
  'companyName' : IDL.Text,
  'category' : IDL.Text,
  'location' : IDL.Text,
  'contactPhone' : IDL.Opt(IDL.Text),
});
export const Note = IDL.Record({
  'id' : NoteId,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'timestamp' : Time,
});
export const Notification = IDL.Record({
  'id' : NotificationId,
  'title' : IDL.Text,
  'notificationType' : IDL.Text,
  'jobId' : IDL.Nat,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const RentalStatus = IDL.Variant({
  'rented' : IDL.Null,
  'available' : IDL.Null,
});
export const RentalProperty = IDL.Record({
  'id' : RentalPropertyId,
  'status' : RentalStatus,
  'title' : IDL.Text,
  'ownerName' : IDL.Text,
  'createdAt' : Time,
  'numberOfRooms' : IDL.Nat,
  'description' : IDL.Text,
  'pricePerMonth' : IDL.Float64,
  'location' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const ScheduleEntry = IDL.Record({
  'id' : ScheduleId,
  'startTime' : IDL.Nat,
  'title' : IDL.Text,
  'endTime' : IDL.Nat,
  'dayOfWeek' : DayOfWeek,
  'notes' : IDL.Text,
});
export const Task = IDL.Record({
  'id' : TaskId,
  'title' : IDL.Text,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(Time),
  'description' : IDL.Text,
  'priority' : Priority,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'worker' : IDL.Null,
});
export const UserAccount = IDL.Record({
  'id' : IDL.Nat,
  'emailOrPhone' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'role' : UserRole,
  'passwordHash' : IDL.Text,
});
export const WorkEntry = IDL.Record({
  'id' : WorkEntryId,
  'startTime' : IDL.Nat,
  'workType' : IDL.Text,
  'dailyPayment' : IDL.Float64,
  'endTime' : IDL.Nat,
  'date' : IDL.Text,
  'hoursWorked' : IDL.Float64,
  'createdAt' : Time,
  'notes' : IDL.Text,
  'workerName' : IDL.Text,
});
export const JobApplication = IDL.Record({
  'id' : JobApplicationId,
  'status' : IDL.Text,
  'appliedAt' : Time,
  'applicantName' : IDL.Text,
  'applicantPhone' : IDL.Text,
  'vacancyId' : JobVacancyId,
  'postedByUserId' : IDL.Nat,
  'applicantUserId' : IDL.Nat,
});
export const RentalWithOwner = IDL.Record({
  'id' : RentalPropertyId,
  'status' : RentalStatus,
  'title' : IDL.Text,
  'ownerName' : IDL.Text,
  'createdAt' : Time,
  'numberOfRooms' : IDL.Nat,
  'description' : IDL.Text,
  'postedByUserId' : IDL.Nat,
  'pricePerMonth' : IDL.Float64,
  'location' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : BookingId,
  'status' : BookingStatus,
  'serviceType' : IDL.Text,
  'workerId' : IDL.Nat,
  'userId' : IDL.Nat,
  'note' : IDL.Text,
  'createdAt' : Time,
  'workerName' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'userId' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserNotification = IDL.Record({
  'id' : UserNotificationId,
  'title' : IDL.Text,
  'receiverUserId' : IDL.Nat,
  'jobId' : IDL.Nat,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'senderUserId' : IDL.Nat,
});
export const UserId = IDL.Nat;
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptBooking' : IDL.Func([BookingId], [IDL.Bool], []),
  'applyToVacancy' : IDL.Func(
      [JobVacancyId, IDL.Nat, IDL.Text, IDL.Text],
      [JobApplicationId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'assignJobPosting' : IDL.Func(
      [JobPostingId, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'cancelBooking' : IDL.Func([BookingId], [IDL.Bool], []),
  'closeJobVacancy' : IDL.Func([JobVacancyId], [], []),
  'completeJobPosting' : IDL.Func([JobPostingId], [IDL.Bool], []),
  'createBooking' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [BookingId],
      [],
    ),
  'createJobPosting' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Int, IDL.Float64, IDL.Text],
      [JobPostingId],
      [],
    ),
  'createJobVacancy' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Text),
      ],
      [JobVacancyId],
      [],
    ),
  'createNote' : IDL.Func([IDL.Text, IDL.Text], [NoteId], []),
  'createNotification' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [NotificationId],
      [],
    ),
  'createRentalProperty' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
      ],
      [RentalPropertyId],
      [],
    ),
  'createScheduleEntry' : IDL.Func(
      [IDL.Text, DayOfWeek, IDL.Nat, IDL.Nat, IDL.Text],
      [ScheduleId],
      [],
    ),
  'createTask' : IDL.Func(
      [IDL.Text, IDL.Text, Priority, IDL.Opt(Time)],
      [TaskId],
      [],
    ),
  'createUserNotification' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [UserNotificationId],
      [],
    ),
  'createWorkEntry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
      ],
      [WorkEntryId],
      [],
    ),
  'createWorkerProfile' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteJobVacancy' : IDL.Func([JobVacancyId, IDL.Nat], [], []),
  'deleteNote' : IDL.Func([NoteId], [], []),
  'deleteNotification' : IDL.Func([NotificationId], [], []),
  'deleteRentalProperty' : IDL.Func([RentalPropertyId, IDL.Nat], [], []),
  'deleteScheduleEntry' : IDL.Func([ScheduleId], [], []),
  'deleteTask' : IDL.Func([TaskId], [], []),
  'deleteUserNotification' : IDL.Func([UserNotificationId], [], []),
  'deleteWorkEntry' : IDL.Func([WorkEntryId], [], []),
  'generateOtp' : IDL.Func([IDL.Text], [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })], []),
    'getOtpForPhone' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getActiveWorkers' : IDL.Func([], [IDL.Vec(WorkerProfile)], ['query']),
  'getAllJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
  'getAllJobVacancies' : IDL.Func(
      [],
      [IDL.Vec(JobVacancyWithOwner)],
      ['query'],
    ),
  'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getAllNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getAllRentals' : IDL.Func([], [IDL.Vec(RentalProperty)], ['query']),
  'getAllScheduleEntries' : IDL.Func([], [IDL.Vec(ScheduleEntry)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserAccount)], ['query']),
  'getAllWorkEntries' : IDL.Func([], [IDL.Vec(WorkEntry)], ['query']),
  'getAllWorkerProfiles' : IDL.Func([], [IDL.Vec(WorkerProfile)], ['query']),
  'getApplicationsForVacancy' : IDL.Func(
      [JobVacancyId],
      [IDL.Vec(JobApplication)],
      ['query'],
    ),
  'getAssignedJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
  'getAvailableJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
  'getAvailableRentals' : IDL.Func([], [IDL.Vec(RentalWithOwner)], ['query']),
  'getBookingsForUser' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
  'getBookingsForWorker' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getJobVacanciesByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(JobVacancyWithOwner)],
      ['query'],
    ),
  'getJobVacanciesByLocation' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(JobVacancyWithOwner)],
      ['query'],
    ),
  'getNotInterestedJobIds' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(JobPostingId)],
      ['query'],
    ),
  'getNote' : IDL.Func([NoteId], [Note], ['query']),
  'getNotificationsForUser' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(UserNotification)],
      ['query'],
    ),
  'getOpenJobVacancies' : IDL.Func(
      [],
      [IDL.Vec(JobVacancyWithOwner)],
      ['query'],
    ),
  'getRentalsByLocation' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(RentalProperty)],
      ['query'],
    ),
  'getScheduleEntry' : IDL.Func([ScheduleId], [ScheduleEntry], ['query']),
  'getTask' : IDL.Func([TaskId], [Task], ['query']),
  'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUnreadCountForUser' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getUserApplications' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(JobApplication)],
      ['query'],
    ),
  'getUserById' : IDL.Func([UserId], [IDL.Opt(UserAccount)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkEntriesByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(WorkEntry)],
      ['query'],
    ),
  'getWorkEntriesByDateRange' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(WorkEntry)],
      ['query'],
    ),
  'getWorkEntriesByWorker' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(WorkEntry)],
      ['query'],
    ),
  'getWorkEntry' : IDL.Func([WorkEntryId], [WorkEntry], ['query']),
  'getWorkerProfileByUserId' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(WorkerProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isSmsConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({ 'userId' : UserId, 'role' : UserRole }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'sendLoginOtp' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'loginWithOtp' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({ 'userId' : UserId, 'role' : UserRole }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markAllUserNotificationsRead' : IDL.Func([IDL.Nat], [], []),
  'markNotificationRead' : IDL.Func([NotificationId], [], []),
  'markUserNotificationRead' : IDL.Func([UserNotificationId], [], []),
  'register' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, UserRole],
      [IDL.Variant({ 'ok' : UserId, 'err' : IDL.Text })],
      [],
    ),
  'rejectBooking' : IDL.Func([BookingId], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setJobPreference' : IDL.Func([IDL.Text, JobPostingId, IDL.Bool], [], []),
  'setTwilioConfig' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'setWorkerStatus' : IDL.Func([IDL.Nat, WorkerStatus], [IDL.Bool], []),
  'transformOtpResponse' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateJobVacancy' : IDL.Func(
      [
        JobVacancyId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Nat,
      ],
      [],
      [],
    ),
  'updateNote' : IDL.Func([NoteId, IDL.Text, IDL.Text], [], []),
  'updateRentalStatus' : IDL.Func([RentalPropertyId, RentalStatus], [], []),
  'updateScheduleEntry' : IDL.Func(
      [ScheduleId, IDL.Text, DayOfWeek, IDL.Nat, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'updateTask' : IDL.Func(
      [TaskId, IDL.Text, IDL.Text, Priority, IDL.Opt(Time), IDL.Bool],
      [],
      [],
    ),
  'updateWorkEntry' : IDL.Func(
      [
        WorkEntryId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateWorkerLocation' : IDL.Func(
      [WorkerId, IDL.Float64, IDL.Float64],
      [IDL.Bool],
      [],
    ),
  'updateWorkerStatus' : IDL.Func([WorkerId, IDL.Bool], [IDL.Bool], []),
  'verifyOtp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BookingId = IDL.Nat;
  const JobVacancyId = IDL.Nat;
  const JobApplicationId = IDL.Nat;
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const JobPostingId = IDL.Nat;
  const NoteId = IDL.Nat;
  const NotificationId = IDL.Nat;
  const RentalPropertyId = IDL.Nat;
  const DayOfWeek = IDL.Variant({
    'tuesday' : IDL.Null,
    'wednesday' : IDL.Null,
    'saturday' : IDL.Null,
    'thursday' : IDL.Null,
    'sunday' : IDL.Null,
    'friday' : IDL.Null,
    'monday' : IDL.Null,
  });
  const ScheduleId = IDL.Nat;
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Time = IDL.Int;
  const TaskId = IDL.Nat;
  const UserNotificationId = IDL.Nat;
  const WorkEntryId = IDL.Nat;
  const WorkerId = IDL.Nat;
  const WorkerStatus = IDL.Variant({
    'active' : IDL.Null,
    'blocked' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const WorkerProfile = IDL.Record({
    'id' : WorkerId,
    'status' : WorkerStatus,
    'latitude' : IDL.Float64,
    'userId' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'profession' : IDL.Text,
    'longitude' : IDL.Float64,
    'rating' : IDL.Float64,
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  const JobStatus = IDL.Variant({
    'assigned' : IDL.Null,
    'deleted' : IDL.Null,
    'completed' : IDL.Null,
    'available' : IDL.Null,
  });
  const JobPosting = IDL.Record({
    'id' : JobPostingId,
    'startTime' : IDL.Int,
    'status' : JobStatus,
    'title' : IDL.Text,
    'endTime' : IDL.Int,
    'date' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'address' : IDL.Text,
    'assignedWorkerAddress' : IDL.Text,
    'assignedWorkerPhone' : IDL.Text,
    'assignedWorkerName' : IDL.Text,
    'paymentAmount' : IDL.Float64,
  });
  const JobVacancyStatus = IDL.Variant({
    'closed' : IDL.Null,
    'open' : IDL.Null,
  });
  const JobVacancyWithOwner = IDL.Record({
    'id' : JobVacancyId,
    'status' : JobVacancyStatus,
    'title' : IDL.Text,
    'postedAt' : Time,
    'salary' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'postedByUserId' : IDL.Nat,
    'companyName' : IDL.Text,
    'category' : IDL.Text,
    'location' : IDL.Text,
    'contactPhone' : IDL.Opt(IDL.Text),
  });
  const Note = IDL.Record({
    'id' : NoteId,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'timestamp' : Time,
  });
  const Notification = IDL.Record({
    'id' : NotificationId,
    'title' : IDL.Text,
    'notificationType' : IDL.Text,
    'jobId' : IDL.Nat,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const RentalStatus = IDL.Variant({
    'rented' : IDL.Null,
    'available' : IDL.Null,
  });
  const RentalProperty = IDL.Record({
    'id' : RentalPropertyId,
    'status' : RentalStatus,
    'title' : IDL.Text,
    'ownerName' : IDL.Text,
    'createdAt' : Time,
    'numberOfRooms' : IDL.Nat,
    'description' : IDL.Text,
    'pricePerMonth' : IDL.Float64,
    'location' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const ScheduleEntry = IDL.Record({
    'id' : ScheduleId,
    'startTime' : IDL.Nat,
    'title' : IDL.Text,
    'endTime' : IDL.Nat,
    'dayOfWeek' : DayOfWeek,
    'notes' : IDL.Text,
  });
  const Task = IDL.Record({
    'id' : TaskId,
    'title' : IDL.Text,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(Time),
    'description' : IDL.Text,
    'priority' : Priority,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'worker' : IDL.Null,
  });
  const UserAccount = IDL.Record({
    'id' : IDL.Nat,
    'emailOrPhone' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'role' : UserRole,
    'passwordHash' : IDL.Text,
  });
  const WorkEntry = IDL.Record({
    'id' : WorkEntryId,
    'startTime' : IDL.Nat,
    'workType' : IDL.Text,
    'dailyPayment' : IDL.Float64,
    'endTime' : IDL.Nat,
    'date' : IDL.Text,
    'hoursWorked' : IDL.Float64,
    'createdAt' : Time,
    'notes' : IDL.Text,
    'workerName' : IDL.Text,
  });
  const JobApplication = IDL.Record({
    'id' : JobApplicationId,
    'status' : IDL.Text,
    'appliedAt' : Time,
    'applicantName' : IDL.Text,
    'applicantPhone' : IDL.Text,
    'vacancyId' : JobVacancyId,
    'postedByUserId' : IDL.Nat,
    'applicantUserId' : IDL.Nat,
  });
  const RentalWithOwner = IDL.Record({
    'id' : RentalPropertyId,
    'status' : RentalStatus,
    'title' : IDL.Text,
    'ownerName' : IDL.Text,
    'createdAt' : Time,
    'numberOfRooms' : IDL.Nat,
    'description' : IDL.Text,
    'postedByUserId' : IDL.Nat,
    'pricePerMonth' : IDL.Float64,
    'location' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : BookingId,
    'status' : BookingStatus,
    'serviceType' : IDL.Text,
    'workerId' : IDL.Nat,
    'userId' : IDL.Nat,
    'note' : IDL.Text,
    'createdAt' : Time,
    'workerName' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'userId' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserNotification = IDL.Record({
    'id' : UserNotificationId,
    'title' : IDL.Text,
    'receiverUserId' : IDL.Nat,
    'jobId' : IDL.Nat,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'senderUserId' : IDL.Nat,
  });
  const UserId = IDL.Nat;
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptBooking' : IDL.Func([BookingId], [IDL.Bool], []),
    'applyToVacancy' : IDL.Func(
        [JobVacancyId, IDL.Nat, IDL.Text, IDL.Text],
        [JobApplicationId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'assignJobPosting' : IDL.Func(
        [JobPostingId, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'cancelBooking' : IDL.Func([BookingId], [IDL.Bool], []),
    'closeJobVacancy' : IDL.Func([JobVacancyId], [], []),
    'completeJobPosting' : IDL.Func([JobPostingId], [IDL.Bool], []),
    'createBooking' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [BookingId],
        [],
      ),
    'createJobPosting' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Int, IDL.Float64, IDL.Text],
        [JobPostingId],
        [],
      ),
    'createJobVacancy' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Text),
        ],
        [JobVacancyId],
        [],
      ),
    'createNote' : IDL.Func([IDL.Text, IDL.Text], [NoteId], []),
    'createNotification' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [NotificationId],
        [],
      ),
    'createRentalProperty' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
        ],
        [RentalPropertyId],
        [],
      ),
    'createScheduleEntry' : IDL.Func(
        [IDL.Text, DayOfWeek, IDL.Nat, IDL.Nat, IDL.Text],
        [ScheduleId],
        [],
      ),
    'createTask' : IDL.Func(
        [IDL.Text, IDL.Text, Priority, IDL.Opt(Time)],
        [TaskId],
        [],
      ),
    'createUserNotification' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [UserNotificationId],
        [],
      ),
    'createWorkEntry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
        ],
        [WorkEntryId],
        [],
      ),
    'createWorkerProfile' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteJobVacancy' : IDL.Func([JobVacancyId, IDL.Nat], [], []),
    'deleteNote' : IDL.Func([NoteId], [], []),
    'deleteNotification' : IDL.Func([NotificationId], [], []),
    'deleteRentalProperty' : IDL.Func([RentalPropertyId, IDL.Nat], [], []),
    'deleteScheduleEntry' : IDL.Func([ScheduleId], [], []),
    'deleteTask' : IDL.Func([TaskId], [], []),
    'deleteUserNotification' : IDL.Func([UserNotificationId], [], []),
    'deleteWorkEntry' : IDL.Func([WorkEntryId], [], []),
    'generateOtp' : IDL.Func([IDL.Text], [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })], []),
    'getOtpForPhone' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getActiveWorkers' : IDL.Func([], [IDL.Vec(WorkerProfile)], ['query']),
    'getAllJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
    'getAllJobVacancies' : IDL.Func(
        [],
        [IDL.Vec(JobVacancyWithOwner)],
        ['query'],
      ),
    'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getAllNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getAllRentals' : IDL.Func([], [IDL.Vec(RentalProperty)], ['query']),
    'getAllScheduleEntries' : IDL.Func([], [IDL.Vec(ScheduleEntry)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserAccount)], ['query']),
    'getAllWorkEntries' : IDL.Func([], [IDL.Vec(WorkEntry)], ['query']),
    'getAllWorkerProfiles' : IDL.Func([], [IDL.Vec(WorkerProfile)], ['query']),
    'getApplicationsForVacancy' : IDL.Func(
        [JobVacancyId],
        [IDL.Vec(JobApplication)],
        ['query'],
      ),
    'getAssignedJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
    'getAvailableJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
    'getAvailableRentals' : IDL.Func([], [IDL.Vec(RentalWithOwner)], ['query']),
    'getBookingsForUser' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
    'getBookingsForWorker' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getJobVacanciesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(JobVacancyWithOwner)],
        ['query'],
      ),
    'getJobVacanciesByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(JobVacancyWithOwner)],
        ['query'],
      ),
    'getNotInterestedJobIds' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(JobPostingId)],
        ['query'],
      ),
    'getNote' : IDL.Func([NoteId], [Note], ['query']),
    'getNotificationsForUser' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(UserNotification)],
        ['query'],
      ),
    'getOpenJobVacancies' : IDL.Func(
        [],
        [IDL.Vec(JobVacancyWithOwner)],
        ['query'],
      ),
    'getRentalsByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(RentalProperty)],
        ['query'],
      ),
    'getScheduleEntry' : IDL.Func([ScheduleId], [ScheduleEntry], ['query']),
    'getTask' : IDL.Func([TaskId], [Task], ['query']),
    'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUnreadCountForUser' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getUserApplications' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(JobApplication)],
        ['query'],
      ),
    'getUserById' : IDL.Func([UserId], [IDL.Opt(UserAccount)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkEntriesByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(WorkEntry)],
        ['query'],
      ),
    'getWorkEntriesByDateRange' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(WorkEntry)],
        ['query'],
      ),
    'getWorkEntriesByWorker' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(WorkEntry)],
        ['query'],
      ),
    'getWorkEntry' : IDL.Func([WorkEntryId], [WorkEntry], ['query']),
    'getWorkerProfileByUserId' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(WorkerProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isSmsConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({ 'userId' : UserId, 'role' : UserRole }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'sendLoginOtp' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'loginWithOtp' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({ 'userId' : UserId, 'role' : UserRole }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markAllUserNotificationsRead' : IDL.Func([IDL.Nat], [], []),
    'markNotificationRead' : IDL.Func([NotificationId], [], []),
    'markUserNotificationRead' : IDL.Func([UserNotificationId], [], []),
    'register' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, UserRole],
        [IDL.Variant({ 'ok' : UserId, 'err' : IDL.Text })],
        [],
      ),
    'rejectBooking' : IDL.Func([BookingId], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setJobPreference' : IDL.Func([IDL.Text, JobPostingId, IDL.Bool], [], []),
    'setTwilioConfig' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'setWorkerStatus' : IDL.Func([IDL.Nat, WorkerStatus], [IDL.Bool], []),
    'transformOtpResponse' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateJobVacancy' : IDL.Func(
        [
          JobVacancyId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'updateNote' : IDL.Func([NoteId, IDL.Text, IDL.Text], [], []),
    'updateRentalStatus' : IDL.Func([RentalPropertyId, RentalStatus], [], []),
    'updateScheduleEntry' : IDL.Func(
        [ScheduleId, IDL.Text, DayOfWeek, IDL.Nat, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'updateTask' : IDL.Func(
        [TaskId, IDL.Text, IDL.Text, Priority, IDL.Opt(Time), IDL.Bool],
        [],
        [],
      ),
    'updateWorkEntry' : IDL.Func(
        [
          WorkEntryId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateWorkerLocation' : IDL.Func(
        [WorkerId, IDL.Float64, IDL.Float64],
        [IDL.Bool],
        [],
      ),
    'updateWorkerStatus' : IDL.Func([WorkerId, IDL.Bool], [IDL.Bool], []),
    'verifyOtp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };