/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Note {
    id: NoteId;
    title: string;
    body: string;
    timestamp: Time;
}
export type NoteId = bigint;
export interface WorkEntry {
    id: WorkEntryId;
    startTime: bigint;
    workType: string;
    dailyPayment: number;
    endTime: bigint;
    date: string;
    hoursWorked: number;
    createdAt: Time;
    notes: string;
    workerName: string;
}
export type Time = bigint;
export interface ScheduleEntry {
    id: ScheduleId;
    startTime: bigint;
    title: string;
    endTime: bigint;
    dayOfWeek: DayOfWeek;
    notes: string;
}
export type JobVacancyId = bigint;
export interface Task {
    id: TaskId;
    title: string;
    completed: boolean;
    dueDate?: Time;
    description: string;
    priority: Priority;
}
export interface JobVacancy {
    id: JobVacancyId;
    status: JobVacancyStatus;
    title: string;
    postedAt: Time;
    salary?: string;
    description: string;
    companyName: string;
    category: string;
    location: string;
}
export interface JobPosting {
    id: JobPostingId;
    startTime: bigint;
    status: JobStatus;
    title: string;
    endTime: bigint;
    date: string;
    createdAt: Time;
    description: string;
    address: string;
    assignedWorkerAddress: string;
    assignedWorkerPhone: string;
    assignedWorkerName: string;
    paymentAmount: number;
}
export type JobApplicationId = bigint;
export interface JobApplication {
    id: JobApplicationId;
    appliedAt: Time;
    applicantName: string;
    applicantPhone: string;
    vacancyId: JobVacancyId;
}
export type RentalPropertyId = bigint;
export type WorkEntryId = bigint;
export type ScheduleId = bigint;
export type TaskId = bigint;
export type NotificationId = bigint;
export interface Notification {
    id: NotificationId;
    title: string;
    notificationType: string;
    jobId: bigint;
    isRead: boolean;
    message: string;
    timestamp: Time;
}
export type JobPostingId = bigint;
export interface RentalProperty {
    id: RentalPropertyId;
    status: RentalStatus;
    title: string;
    ownerName: string;
    createdAt: Time;
    numberOfRooms: bigint;
    description: string;
    pricePerMonth: number;
    location: string;
    contactPhone: string;
}
export enum DayOfWeek {
    tuesday = "tuesday",
    wednesday = "wednesday",
    saturday = "saturday",
    thursday = "thursday",
    sunday = "sunday",
    friday = "friday",
    monday = "monday"
}
export enum JobStatus {
    assigned = "assigned",
    deleted = "deleted",
    completed = "completed",
    available = "available"
}
export enum JobVacancyStatus {
    closed = "closed",
    open = "open"
}
export enum Priority {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum RentalStatus {
    rented = "rented",
    available = "available"
}
export interface backendInterface {
    applyToVacancy(vacancyId: JobVacancyId, applicantName: string, applicantPhone: string): Promise<JobApplicationId>;
    assignJobPosting(id: JobPostingId, workerName: string, workerPhone: string, workerAddress: string): Promise<boolean>;
    closeJobVacancy(id: JobVacancyId): Promise<void>;
    completeJobPosting(id: JobPostingId): Promise<boolean>;
    createJobPosting(title: string, description: string, date: string, startTime: bigint, endTime: bigint, paymentAmount: number, address: string): Promise<JobPostingId>;
    createJobVacancy(title: string, companyName: string, category: string, salary: string | null, location: string, description: string): Promise<JobVacancyId>;
    createNote(title: string, body: string): Promise<NoteId>;
    createNotification(title: string, message: string, notificationType: string, jobId: bigint): Promise<NotificationId>;
    createRentalProperty(title: string, description: string, location: string, pricePerMonth: number, numberOfRooms: bigint, contactPhone: string, ownerName: string): Promise<RentalPropertyId>;
    createScheduleEntry(title: string, dayOfWeek: DayOfWeek, startTime: bigint, endTime: bigint, notes: string): Promise<ScheduleId>;
    createTask(title: string, description: string, priority: Priority, dueDate: Time | null): Promise<TaskId>;
    createWorkEntry(workerName: string, date: string, workType: string, startTime: bigint, endTime: bigint, hoursWorked: number, dailyPayment: number, notes: string): Promise<WorkEntryId>;
    deleteJobPosting(id: JobPostingId): Promise<void>;
    deleteJobVacancy(id: JobVacancyId): Promise<void>;
    deleteNote(noteId: NoteId): Promise<void>;
    deleteNotification(id: NotificationId): Promise<void>;
    deleteRentalProperty(id: RentalPropertyId): Promise<void>;
    deleteScheduleEntry(entryId: ScheduleId): Promise<void>;
    deleteTask(taskId: TaskId): Promise<void>;
    deleteWorkEntry(entryId: WorkEntryId): Promise<void>;
    getAllJobPostings(): Promise<Array<JobPosting>>;
    getAllJobVacancies(): Promise<Array<JobVacancy>>;
    getAllNotes(): Promise<Array<Note>>;
    getAllNotifications(): Promise<Array<Notification>>;
    getAllRentals(): Promise<Array<RentalProperty>>;
    getAllScheduleEntries(): Promise<Array<ScheduleEntry>>;
    getAllTasks(): Promise<Array<Task>>;
    getAllWorkEntries(): Promise<Array<WorkEntry>>;
    getApplicationsForVacancy(vacancyId: JobVacancyId): Promise<Array<JobApplication>>;
    getAssignedJobPostings(): Promise<Array<JobPosting>>;
    getAvailableJobPostings(): Promise<Array<JobPosting>>;
    getAvailableJobPostingsForWorker(workerId: string): Promise<Array<JobPosting>>;
    getAvailableRentals(): Promise<Array<RentalProperty>>;
    getJobVacanciesByCategory(category: string): Promise<Array<JobVacancy>>;
    getJobVacanciesByLocation(location: string): Promise<Array<JobVacancy>>;
    getNotInterestedJobIds(workerId: string): Promise<Array<JobPostingId>>;
    getNote(noteId: NoteId): Promise<Note>;
    getOpenJobVacancies(): Promise<Array<JobVacancy>>;
    getRentalsByLocation(location: string): Promise<Array<RentalProperty>>;
    getScheduleEntry(entryId: ScheduleId): Promise<ScheduleEntry>;
    getTask(taskId: TaskId): Promise<Task>;
    getUnreadCount(): Promise<bigint>;
    getWorkEntriesByDate(date: string): Promise<Array<WorkEntry>>;
    getWorkEntriesByDateRange(fromDate: string, toDate: string): Promise<Array<WorkEntry>>;
    getWorkEntriesByWorker(workerName: string): Promise<Array<WorkEntry>>;
    getWorkEntry(entryId: WorkEntryId): Promise<WorkEntry>;
    markAllNotificationsRead(): Promise<void>;
    markNotificationRead(id: NotificationId): Promise<void>;
    setJobPreference(workerId: string, jobId: JobPostingId, interested: boolean): Promise<void>;
    updateNote(noteId: NoteId, title: string, body: string): Promise<void>;
    updateRentalStatus(id: RentalPropertyId, status: RentalStatus): Promise<void>;
    updateScheduleEntry(entryId: ScheduleId, title: string, dayOfWeek: DayOfWeek, startTime: bigint, endTime: bigint, notes: string): Promise<void>;
    updateTask(taskId: TaskId, title: string, description: string, priority: Priority, dueDate: Time | null, completed: boolean): Promise<void>;
    updateWorkEntry(entryId: WorkEntryId, workerName: string, date: string, workType: string, startTime: bigint, endTime: bigint, hoursWorked: number, dailyPayment: number, notes: string): Promise<void>;
}
import type { DayOfWeek as _DayOfWeek, JobPosting as _JobPosting, JobPostingId as _JobPostingId, JobStatus as _JobStatus, JobVacancy as _JobVacancy, JobVacancyId as _JobVacancyId, JobVacancyStatus as _JobVacancyStatus, Priority as _Priority, RentalProperty as _RentalProperty, RentalPropertyId as _RentalPropertyId, RentalStatus as _RentalStatus, ScheduleEntry as _ScheduleEntry, ScheduleId as _ScheduleId, Task as _Task, TaskId as _TaskId, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async applyToVacancy(arg0: JobVacancyId, arg1: string, arg2: string): Promise<JobApplicationId> {
        if (this.processError) {
            try {
                const result = await this.actor.applyToVacancy(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyToVacancy(arg0, arg1, arg2);
            return result;
        }
    }
    async assignJobPosting(arg0: JobPostingId, arg1: string, arg2: string, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.assignJobPosting(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignJobPosting(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async closeJobVacancy(arg0: JobVacancyId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.closeJobVacancy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.closeJobVacancy(arg0);
            return result;
        }
    }
    async completeJobPosting(arg0: JobPostingId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.completeJobPosting(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeJobPosting(arg0);
            return result;
        }
    }
    async createJobPosting(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: number, arg6: string): Promise<JobPostingId> {
        if (this.processError) {
            try {
                const result = await this.actor.createJobPosting(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJobPosting(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createJobVacancy(arg0: string, arg1: string, arg2: string, arg3: string | null, arg4: string, arg5: string): Promise<JobVacancyId> {
        if (this.processError) {
            try {
                const result = await this.actor.createJobVacancy(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJobVacancy(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
    async createNote(arg0: string, arg1: string): Promise<NoteId> {
        if (this.processError) {
            try {
                const result = await this.actor.createNote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNote(arg0, arg1);
            return result;
        }
    }
    async createNotification(arg0: string, arg1: string, arg2: string, arg3: bigint): Promise<NotificationId> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotification(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotification(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createRentalProperty(arg0: string, arg1: string, arg2: string, arg3: number, arg4: bigint, arg5: string, arg6: string): Promise<RentalPropertyId> {
        if (this.processError) {
            try {
                const result = await this.actor.createRentalProperty(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRentalProperty(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createScheduleEntry(arg0: string, arg1: DayOfWeek, arg2: bigint, arg3: bigint, arg4: string): Promise<ScheduleId> {
        if (this.processError) {
            try {
                const result = await this.actor.createScheduleEntry(arg0, to_candid_DayOfWeek_n2(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createScheduleEntry(arg0, to_candid_DayOfWeek_n2(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return result;
        }
    }
    async createTask(arg0: string, arg1: string, arg2: Priority, arg3: Time | null): Promise<TaskId> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, arg1, to_candid_Priority_n4(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, arg1, to_candid_Priority_n4(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async createWorkEntry(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: number, arg6: number, arg7: string): Promise<WorkEntryId> {
        if (this.processError) {
            try {
                const result = await this.actor.createWorkEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWorkEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async deleteJobPosting(arg0: JobPostingId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJobPosting(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJobPosting(arg0);
            return result;
        }
    }
    async deleteJobVacancy(arg0: JobVacancyId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJobVacancy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJobVacancy(arg0);
            return result;
        }
    }
    async deleteNote(arg0: NoteId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNote(arg0);
            return result;
        }
    }
    async deleteNotification(arg0: NotificationId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNotification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNotification(arg0);
            return result;
        }
    }
    async deleteRentalProperty(arg0: RentalPropertyId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRentalProperty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRentalProperty(arg0);
            return result;
        }
    }
    async deleteScheduleEntry(arg0: ScheduleId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteScheduleEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteScheduleEntry(arg0);
            return result;
        }
    }
    async deleteTask(arg0: TaskId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async deleteWorkEntry(arg0: WorkEntryId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWorkEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWorkEntry(arg0);
            return result;
        }
    }
    async getAllJobPostings(): Promise<Array<JobPosting>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJobPostings();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJobPostings();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllJobVacancies(): Promise<Array<JobVacancy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJobVacancies();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJobVacancies();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNotes(): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNotes();
            return result;
        }
    }
    async getAllNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNotifications();
            return result;
        }
    }
    async getAllRentals(): Promise<Array<RentalProperty>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRentals();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRentals();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllScheduleEntries(): Promise<Array<ScheduleEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllScheduleEntries();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllScheduleEntries();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasks();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasks();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllWorkEntries(): Promise<Array<WorkEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWorkEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWorkEntries();
            return result;
        }
    }
    async getApplicationsForVacancy(arg0: JobVacancyId): Promise<Array<JobApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplicationsForVacancy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplicationsForVacancy(arg0);
            return result;
        }
    }
    async getAssignedJobPostings(): Promise<Array<JobPosting>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssignedJobPostings();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssignedJobPostings();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableJobPostings(): Promise<Array<JobPosting>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableJobPostings();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableJobPostings();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableJobPostingsForWorker(arg0: string): Promise<Array<JobPosting>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableJobPostingsForWorker(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableJobPostingsForWorker(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableRentals(): Promise<Array<RentalProperty>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableRentals();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableRentals();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobVacanciesByCategory(arg0: string): Promise<Array<JobVacancy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobVacanciesByCategory(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobVacanciesByCategory(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobVacanciesByLocation(arg0: string): Promise<Array<JobVacancy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobVacanciesByLocation(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobVacanciesByLocation(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotInterestedJobIds(arg0: string): Promise<Array<JobPostingId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotInterestedJobIds(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotInterestedJobIds(arg0);
            return result;
        }
    }
    async getNote(arg0: NoteId): Promise<Note> {
        if (this.processError) {
            try {
                const result = await this.actor.getNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNote(arg0);
            return result;
        }
    }
    async getOpenJobVacancies(): Promise<Array<JobVacancy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpenJobVacancies();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpenJobVacancies();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRentalsByLocation(arg0: string): Promise<Array<RentalProperty>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRentalsByLocation(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRentalsByLocation(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScheduleEntry(arg0: ScheduleId): Promise<ScheduleEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.getScheduleEntry(arg0);
                return from_candid_ScheduleEntry_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScheduleEntry(arg0);
            return from_candid_ScheduleEntry_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTask(arg0: TaskId): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.getTask(arg0);
                return from_candid_Task_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTask(arg0);
            return from_candid_Task_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadCount();
            return result;
        }
    }
    async getWorkEntriesByDate(arg0: string): Promise<Array<WorkEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkEntriesByDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkEntriesByDate(arg0);
            return result;
        }
    }
    async getWorkEntriesByDateRange(arg0: string, arg1: string): Promise<Array<WorkEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkEntriesByDateRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkEntriesByDateRange(arg0, arg1);
            return result;
        }
    }
    async getWorkEntriesByWorker(arg0: string): Promise<Array<WorkEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkEntriesByWorker(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkEntriesByWorker(arg0);
            return result;
        }
    }
    async getWorkEntry(arg0: WorkEntryId): Promise<WorkEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkEntry(arg0);
            return result;
        }
    }
    async markAllNotificationsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsRead();
            return result;
        }
    }
    async markNotificationRead(arg0: NotificationId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async setJobPreference(arg0: string, arg1: JobPostingId, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setJobPreference(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setJobPreference(arg0, arg1, arg2);
            return result;
        }
    }
    async updateNote(arg0: NoteId, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNote(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNote(arg0, arg1, arg2);
            return result;
        }
    }
    async updateRentalStatus(arg0: RentalPropertyId, arg1: RentalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRentalStatus(arg0, to_candid_RentalStatus_n34(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRentalStatus(arg0, to_candid_RentalStatus_n34(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateScheduleEntry(arg0: ScheduleId, arg1: string, arg2: DayOfWeek, arg3: bigint, arg4: bigint, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateScheduleEntry(arg0, arg1, to_candid_DayOfWeek_n2(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateScheduleEntry(arg0, arg1, to_candid_DayOfWeek_n2(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5);
            return result;
        }
    }
    async updateTask(arg0: TaskId, arg1: string, arg2: string, arg3: Priority, arg4: Time | null, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, arg1, arg2, to_candid_Priority_n4(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, arg1, arg2, to_candid_Priority_n4(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n6(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async updateWorkEntry(arg0: WorkEntryId, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: bigint, arg6: number, arg7: number, arg8: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkEntry(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
}
function from_candid_DayOfWeek_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DayOfWeek): DayOfWeek {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_JobPosting_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobPosting): JobPosting {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_JobStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobStatus): JobStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_JobVacancyStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobVacancyStatus): JobVacancyStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_JobVacancy_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobVacancy): JobVacancy {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Priority_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Priority): Priority {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_RentalProperty_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RentalProperty): RentalProperty {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_RentalStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RentalStatus): RentalStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ScheduleEntry_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScheduleEntry): ScheduleEntry {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _JobVacancyId;
    status: _JobVacancyStatus;
    title: string;
    postedAt: _Time;
    salary: [] | [string];
    description: string;
    companyName: string;
    category: string;
    location: string;
}): {
    id: JobVacancyId;
    status: JobVacancyStatus;
    title: string;
    postedAt: Time;
    salary?: string;
    description: string;
    companyName: string;
    category: string;
    location: string;
} {
    return {
        id: value.id,
        status: from_candid_JobVacancyStatus_n15(_uploadFile, _downloadFile, value.status),
        title: value.title,
        postedAt: value.postedAt,
        salary: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.salary)),
        description: value.description,
        companyName: value.companyName,
        category: value.category,
        location: value.location
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RentalPropertyId;
    status: _RentalStatus;
    title: string;
    ownerName: string;
    createdAt: _Time;
    numberOfRooms: bigint;
    description: string;
    pricePerMonth: number;
    location: string;
    contactPhone: string;
}): {
    id: RentalPropertyId;
    status: RentalStatus;
    title: string;
    ownerName: string;
    createdAt: Time;
    numberOfRooms: bigint;
    description: string;
    pricePerMonth: number;
    location: string;
    contactPhone: string;
} {
    return {
        id: value.id,
        status: from_candid_RentalStatus_n21(_uploadFile, _downloadFile, value.status),
        title: value.title,
        ownerName: value.ownerName,
        createdAt: value.createdAt,
        numberOfRooms: value.numberOfRooms,
        description: value.description,
        pricePerMonth: value.pricePerMonth,
        location: value.location,
        contactPhone: value.contactPhone
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ScheduleId;
    startTime: bigint;
    title: string;
    endTime: bigint;
    dayOfWeek: _DayOfWeek;
    notes: string;
}): {
    id: ScheduleId;
    startTime: bigint;
    title: string;
    endTime: bigint;
    dayOfWeek: DayOfWeek;
    notes: string;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        title: value.title,
        endTime: value.endTime,
        dayOfWeek: from_candid_DayOfWeek_n26(_uploadFile, _downloadFile, value.dayOfWeek),
        notes: value.notes
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TaskId;
    title: string;
    completed: boolean;
    dueDate: [] | [_Time];
    description: string;
    priority: _Priority;
}): {
    id: TaskId;
    title: string;
    completed: boolean;
    dueDate?: Time;
    description: string;
    priority: Priority;
} {
    return {
        id: value.id,
        title: value.title,
        completed: value.completed,
        dueDate: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.dueDate)),
        description: value.description,
        priority: from_candid_Priority_n32(_uploadFile, _downloadFile, value.priority)
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _JobPostingId;
    startTime: bigint;
    status: _JobStatus;
    title: string;
    endTime: bigint;
    date: string;
    createdAt: _Time;
    description: string;
    address: string;
    assignedWorkerAddress: string;
    assignedWorkerPhone: string;
    assignedWorkerName: string;
    paymentAmount: number;
}): {
    id: JobPostingId;
    startTime: bigint;
    status: JobStatus;
    title: string;
    endTime: bigint;
    date: string;
    createdAt: Time;
    description: string;
    address: string;
    assignedWorkerAddress: string;
    assignedWorkerPhone: string;
    assignedWorkerName: string;
    paymentAmount: number;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        status: from_candid_JobStatus_n10(_uploadFile, _downloadFile, value.status),
        title: value.title,
        endTime: value.endTime,
        date: value.date,
        createdAt: value.createdAt,
        description: value.description,
        address: value.address,
        assignedWorkerAddress: value.assignedWorkerAddress,
        assignedWorkerPhone: value.assignedWorkerPhone,
        assignedWorkerName: value.assignedWorkerName,
        paymentAmount: value.paymentAmount
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    assigned: null;
} | {
    deleted: null;
} | {
    completed: null;
} | {
    available: null;
}): JobStatus {
    return "assigned" in value ? JobStatus.assigned : "deleted" in value ? JobStatus.deleted : "completed" in value ? JobStatus.completed : "available" in value ? JobStatus.available : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    open: null;
}): JobVacancyStatus {
    return "closed" in value ? JobVacancyStatus.closed : "open" in value ? JobVacancyStatus.open : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rented: null;
} | {
    available: null;
}): RentalStatus {
    return "rented" in value ? RentalStatus.rented : "available" in value ? RentalStatus.available : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tuesday: null;
} | {
    wednesday: null;
} | {
    saturday: null;
} | {
    thursday: null;
} | {
    sunday: null;
} | {
    friday: null;
} | {
    monday: null;
}): DayOfWeek {
    return "tuesday" in value ? DayOfWeek.tuesday : "wednesday" in value ? DayOfWeek.wednesday : "saturday" in value ? DayOfWeek.saturday : "thursday" in value ? DayOfWeek.thursday : "sunday" in value ? DayOfWeek.sunday : "friday" in value ? DayOfWeek.friday : "monday" in value ? DayOfWeek.monday : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): Priority {
    return "low" in value ? Priority.low : "high" in value ? Priority.high : "medium" in value ? Priority.medium : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobVacancy>): Array<JobVacancy> {
    return value.map((x)=>from_candid_JobVacancy_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RentalProperty>): Array<RentalProperty> {
    return value.map((x)=>from_candid_RentalProperty_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ScheduleEntry>): Array<ScheduleEntry> {
    return value.map((x)=>from_candid_ScheduleEntry_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobPosting>): Array<JobPosting> {
    return value.map((x)=>from_candid_JobPosting_n8(_uploadFile, _downloadFile, x));
}
function to_candid_DayOfWeek_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DayOfWeek): _DayOfWeek {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_Priority_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): _Priority {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_RentalStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RentalStatus): _RentalStatus {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DayOfWeek): {
    tuesday: null;
} | {
    wednesday: null;
} | {
    saturday: null;
} | {
    thursday: null;
} | {
    sunday: null;
} | {
    friday: null;
} | {
    monday: null;
} {
    return value == DayOfWeek.tuesday ? {
        tuesday: null
    } : value == DayOfWeek.wednesday ? {
        wednesday: null
    } : value == DayOfWeek.saturday ? {
        saturday: null
    } : value == DayOfWeek.thursday ? {
        thursday: null
    } : value == DayOfWeek.sunday ? {
        sunday: null
    } : value == DayOfWeek.friday ? {
        friday: null
    } : value == DayOfWeek.monday ? {
        monday: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RentalStatus): {
    rented: null;
} | {
    available: null;
} {
    return value == RentalStatus.rented ? {
        rented: null
    } : value == RentalStatus.available ? {
        available: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == Priority.low ? {
        low: null
    } : value == Priority.high ? {
        high: null
    } : value == Priority.medium ? {
        medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
